language: node_js
node_js:
  - 0.10

before_script:
  - "npm install"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "./node_modules/.bin/bower install"
  - "gem install sass"
  - "./node_modules/.bin/brunch b"
  - "./bin/coco-mongodb fork"
  - "node index.js --unittest &"

script:
  - "./node_modules/jasmine-node/bin/jasmine-node test/server/ --coffee --captureExceptions"
  - "./node_modules/karma/bin/karma start --browsers Firefox --single-run"
